version: 2
updates:
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'weekly'
      day: 'saturday'
    commit-message:
      prefix: '🆙 action'
    labels:
      - 'github-action :robot:'

  - package-ecosystem: 'gomod'
    directory: '/'
    schedule:
      interval: 'weekly'
      day: 'saturday'
    commit-message:
      prefix: '🆙 go'
      include: 'scope'
    labels:
      - 'dependency :robot:'
