on:
  pull_request:
  push:
    branches-ignore:
      - main

name: build

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 2

      - name: Checkout PR
        run: git checkout HEAD^2
        if: ${{ github.event_name == 'pull_request' }}

      - name: Set up Go
        uses: actions/setup-go@v2.1.3
        with:
          go-version: 1.14.x

      - name: Get dependencies
        run: go get -v -t -d ./...

      - name: Build
        run: go build -v .
